plugins:
  - jekyll-paginate

permalink:        pretty

title:            CMJB
tagline:          'Software and science and games'
description:      'Software and science and games'
url:              'http://cbosoft.github.io'
baseurl:          '/blog/'

author:
  name:           'Chris Boyle'
  url:            'https://github.com/cbosoft'

paginate:         10
include:
  - img
