# Dependencies
# markdown:         redcarpet
# highlighter:      pygments
plugins:
  - jekyll-paginate

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            CMJB
tagline:          'Ramblings about science and stuff'
description:      'Read this blog for ramblings about whatever has me up at night this week.'
url:              http://cbosoft.github.io
baseurl:          /

author:
  name:           'Chris Boyle'
  url:            https://github.com/cbosoft

paginate:         5

# Custom vars
version:          2.1.0
